blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
]

blog/main/urls.py
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('create', views.create, name='create'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/comment/', views.post_comment, name='post_comment')
]

blog/main/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

class PublishedManager(models.Manager): # создание собственного менеджера как object
    def get_queryset(self):
        return super().get_queryset()\
                        .filter(status=Post.Status.PUBLISHED)

class Post(models.Model):

    class Status(models.TextChoices):
        DRAFT = 'DF', 'Черновик'
        PUBLISHED = 'PB', 'Опубликован'

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,
                            unique_for_date='publish') #для того чтобы в базе данных не могло сохроняться посты с одинаковыми слагами
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2,
                              choices=Status.choices,
                              default=Status.PUBLISHED)
    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['-publish'])
        ]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('main:post_detail',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day,
                             self.slug
                             ])


class Comment(models.Model):
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created']
        indexes = [
            models.Index(fields=['created']),
        ]
    def __str__(self):
        return f'Прокомментировал {self.name} on {self.post}'

blog/main/forms.py
from .models import Post, Comment
from django.forms import ModelForm, TextInput, Textarea

class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'slug', 'author', 'body', 'publish', 'status']
        prepopulated_fields = {'slug': ('title',)}
        widgets = {
            'title': TextInput(attrs={
                'placeholder': 'Название'
            }),
            'slug': TextInput(attrs={
                'placeholder': 'Слаг'
            }),
            'body': Textarea(attrs={
                'placeholder': 'Текст'
            })
        }

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']

blog/main/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Comment
#from django.http import Http404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import PostForm, CommentForm
from django.views.decorators.http import require_POST
def post_list(request):
    post_lists = Post.published.all()
    # постраничная разбивка с 3 постами на старнице
    paginator = Paginator(post_lists, 4)
    page_number = request.GET.get('page')  # если нет по такому юрл постарничной разбивки, переносит на 1 стр
    #posts = paginator.page(page_number)  #вызывая метода page получаем обьекты для желаемой страницы
    try:
        posts = paginator.get_page(page_number)
    except PageNotAnInteger:
        posts = paginator.page('1')
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request,
                  'main/post/list.html',
                  {'posts': posts})

#первый способ если база данных не содержит значение по такому id
#def post_detail(request, id):
#    try:
#       post = Post.published.get(id=id)
#    except Post.DoesNotExist:
#        raise Http404('No post found ')
#
#    return render(request,
#                  'main/post/detail.html',
#                  {'post': post})

# Второй способ если база данных не содержит значение по такому id
def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post,
                             status=Post.Status.PUBLISHED,
                             slug=post,
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)
    comments = post.comments.filter(active=True)
    form = CommentForm()

    return render(request,
                  'main/post/detail.html',
                  {'post': post,
                   'comments': comments,
                   'form': form})



def create(request):
    error = ''
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('main:post_list')
        else:
            error = 'Некорректно заполнено'

    form = PostForm()
    return render(request,
                  'main/post/create.html',
                  {'form': form,
                   'error': error})


@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post,
                             id=post_id,
                             status=Post.Status.PUBLISHED)
    comment = None
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
    return render(request, 'main/post/comment.html',
                  {'post': post,
                   'form': form,
                   'comment': comment})

blog/main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link href="https://fonts.googleapis.com/css?family=Lobster&subset=latin,cyrillic" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
</head>
<body>
    <h1>Мой блог</h1>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
    <div id="sidebar">
        <br>
        <br>
    </div>
</body>
</html>

blog/main/templates/main/post/comment.html
{% extends "main/base.html" %}

{% block title%} Добавить комментарий {% endblock %}

{% block content %}
    {% if comment %}
        <h2> комментарий опубликован </h2>
        <p><a href="{{post.get_absolute_url }}"> Вернуться к посту </a> </p>
    {% else %}
        {%include 'main/post/comment_form.html'%}
    {%endif%}
{% endblock %}

blog/main/templates/main/post/comment_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link href="https://fonts.googleapis.com/css?family=Lobster&subset=latin,cyrillic" rel="stylesheet" type="text/css">
</head>
<body>
<h2>Написать комментарий</h2>
  <form action="{% url "main:post_comment" post.id %}" method="post">
      {{form.as_p}}
      {%csrf_token%}
    <p><input type="submit" value="Отправить"></p>
  </form>
</body>

blog/main/templates/main/post/create.html
{% extends "main/base.html" %}

{% block title%} Добавление поста {% endblock %}

{% block content %}
    <div class="forma">
        <h3>Форма по добавлении поста</h3>
        <form method="post">
            {% csrf_token %}
            <label for="{{ form.title.id_for_label}}"></label>
            {{ form.title }} <br>
            <label for="{{ form.slug.id_for_label}}"></label>
            {{ form.slug }} <br>
            {{ form.author }} <br>
            {{ form.body }} <br>
            {{ form.publish }} <br>
            {{ form.status }} <br>
            <span>{{ error }}</span>
            <button type="submit">Запостить</button>
        </form>
    </div>
    <script>
        function translit(word){
    var answer = '';
    var converter = {
        'а': 'a',    'б': 'b',    'в': 'v',    'г': 'g',    'д': 'd',
        'е': 'e',    'ё': 'e',    'ж': 'zh',   'з': 'z',    'и': 'i',
        'й': 'y',    'к': 'k',    'л': 'l',    'м': 'm',    'н': 'n',
        'о': 'o',    'п': 'p',    'р': 'r',    'с': 's',    'т': 't',
        'у': 'u',    'ф': 'f',    'х': 'h',    'ц': 'c',    'ч': 'ch',
        'ш': 'sh',   'щ': 'sch',  'ь': '',     'ы': 'y',    'ъ': '',
        'э': 'e',    'ю': 'yu',   'я': 'ya',   ':': '',     ';': '',

        'А': 'A',    'Б': 'B',    'В': 'V',    'Г': 'G',    'Д': 'D',
        'Е': 'E',    'Ё': 'E',    'Ж': 'Zh',   'З': 'Z',    'И': 'I',
        'Й': 'Y',    'К': 'K',    'Л': 'L',    'М': 'M',    'Н': 'N',
        'О': 'O',    'П': 'P',    'Р': 'R',    'С': 'S',    'Т': 'T',
        'У': 'U',    'Ф': 'F',    'Х': 'H',    'Ц': 'C',    'Ч': 'Ch',
        'Ш': 'Sh',   'Щ': 'Sch',  'Ь': '',     'Ы': 'Y',    'Ъ': '',
        'Э': 'E',    'Ю': 'Yu',   'Я': 'Ya',   ' ': '-'
    };

    for (var i = 0; i < word.length; ++i ) {
        if (converter[word[i]] == undefined){
            answer += word[i];
        } else {
            answer += converter[word[i]];
        }
    }

    return answer;
}

window.onload = function() {
  let title = document.getElementById('{{ form.title.id_for_label}}');
  let text = document.getElementById('{{ form.slug.id_for_label}}');

  title.addEventListener('input', function() {
    text.value = translit(this.value);
  });
}
    </script>
{% endblock %}

blog/main/templates/main/post/detail.html
{% extends "main/base.html" %}

{% block title%} {{post.title}} {% endblock %}

{% block content %}
<i><p class="date"> Опубликован {{post.publish}} пользователем {{post.author}}</p></i>
    <h2 class="post-name">{{post.title}}</h2>
    {{post.body|linebreaks}}
    {% with comments.count as total_comments %}
        <h2>{{total.comments }} Комментарии {{total_comments|pluralize}}</h2>
    {%endwith%}
    {%include 'main/post/comment_form.html'%}
    {%for comment in comments %}
        <div>
            <p>Комментарий {{forloop.counter}} отправленный пользователем {{comment.name}}</p>
            {{comment.body|linebreaks}}
        </div>
    {%empty%}
            <p>Комментарии отсуствуют</p>
    {%endfor%}
{% endblock %}

blog/main/templates/main/post/list.html
{% extends "main/base.html" %}

{% block title%} Мой блог {% endblock %}

{% block content %}
    {% for post in posts %}
        <div class="post-list">
            <h2 class="post-name">
                <a href = '{{ post.get_absolute_url }}'>
                    {{ post.title }}
                </a>
            </h2>
            <p class="date">
                <i> Опубликован {{post.publish}}, пользователем {{ post.author }} </i>
            </p>
            <b>{{ post.body|truncatewords:30|linebreaks }}</b>
        </div>
    {% endfor %}
    <br>
    <a href="{% url 'main:create' %}"><button class="button1">Добавить пост</button></a> <br>
    {% include "pagination.html" with page=posts %}
{% endblock %}

blog/main/templates/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Назад</a>
        {% endif %}
        <span class="current">
            Страница {{ page.number }} из {{ page.paginator.num_pages }}
        </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Вперед</a>
            <a href="?page={{ page.paginator.num_pages }}">В конец</a>
        {%endif%}
    </span>
</div>